### ISSUE TITLE
About caliko library

### ISSUE THREAD

**Issue by Foruck** [meaten/MotionAug#1]
Thanks for sharing your brilliant project!
I'm trying to reproduce your results, but I meet some problems. It seems that an unmentioned Java library `caliko` is adopted in the provided code. Is the library necessary for running the code? And if it is, would you mind providing some instructions on the installation and configuration of `caliko`?

**Comment by meaten** [comment]
We also thank you gave our code a try!
I'm sorry I forgot to include the java runtime installation for IK library.
I already included how to install in the Dependencies section of README.md.

**Comment by meaten** [comment]
We updated `mpi_run.py` to fix `mpirun` command doesn't run mpi threads!
If you encountered this problem, please pull the updates.
