### ISSUE TITLE
How to modify the hand joint in punch motion?

### ISSUE THREAD

**Issue by ArronChan** [meaten/MotionAug#2]
Thank you for sharing your wonderful work!

In paper, you choose the foot joint to modify the motion for more motion variation. But I am still curious about the performonce on the hand joint.

Sadly I have trouble to change it. Can you please tell me the method to do it?

**Comment by meaten** [comment]
Hi ArronChan!

Thanks for your question.
You can change the target end effector by changing the `--end_effector *` in the arg txt file.
Please see [MotionAug/args/ik_fanshape_grab.txt](https://github.com/meaten/MotionAug/blob/main/args/ik_fanshape_grab.txt) for example.
In this `grab` task, we make several motion patterns by changing the trajectory of a right hand.
