### ISSUE TITLE
Missing class Bvh, in "from bvh import Bvh"

### ISSUE THREAD

**Issue by CaveSpiderLZJ** [meaten/MotionAug#3]
Hi, thanks for your work. I'm trying to reproduce your work for my research. However, when running `data/bvh/align.py`, the Bvh class is missing in `data/bvh/util_bvh.py`. Could you please fix this bug? Thanks very much!
<img width="624" alt="image" src="https://github.com/meaten/MotionAug-CVPR2022/assets/58542079/683167dc-0923-497a-bfd3-16adb5475e2a">

**Comment by meaten** [comment]
Hi, 

I think you don't have a Python package for the bvh file.
Could you try to install it by `pip install bvh=0.3`?

**Comment by CaveSpiderLZJ** [comment]
Thanks! That solved my question. Maybe you can add it to dependencies?
